Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Immigration.Models;

namespace Immigration.Controllers
{
    public class AdminController : Controller
    {
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Index()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                DateTime date = DateTime.Now;
                string d = string.Format("{0:MM/dd/yyyy}", date);

                ViewBag.totalUsers = dc.tblUsers.Count();
                ViewBag.totalHotels = dc.tblHotels.Count();
                ViewBag.totalGuests = dc.tblGuests.Count();

                ViewBag.todaysGuests = dc.tblGuests.Where(g => g.addedDate == d).Count();
                ViewBag.todaysHotels = dc.tblHotels.Where(g => g.addedDate == d).Count();
                ViewBag.todaysUsers = dc.tblUsers.Where(g => g.addedDate == d).Count();

                Getway db = new Getway();
                ViewBag.notSend = db.NotSendGuest(d);
            }
            return View();
        }
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Guest()
        {
            Getway dc = new Getway();
            return View(dc.GuestsList());
        }
        public JsonResult LoadCapitals()
        {
            using (HotelEntities db = new HotelEntities())
            {
                return Json(db.CapitalCities.ToList());
            }
        }
        public JsonResult LoadDistricts(int id)
        {
            Getway db = new Getway();
            return Json(db.LoadDistricts(id));
        }
        public JsonResult LoadHotels(int id)
        {
            Getway db = new Getway();
            return Json(db.LoadHotelsByDistricts(id));
        }
        [HttpPost]
        public ActionResult Guest(string capital, string district, string hotel, string fromDate, string toDate)
        {
            Getway dc = new Getway();
            DateTime date = DateTime.Now;
            int cap, dis, hot;
            string fDate = string.Format("{0:MM/dd/yyyy}", date);
            string tDate = string.Format("{0:MM/dd/yyyy}", date);
            if (fromDate != "" || fromDate != null)
            {
                fDate = fromDate;
            }
            if (toDate == "" || toDate == null)
            {
                tDate = toDate;
            }
            if (capital == "" || capital == null)
            {
                cap = 0;
            }
            else
            {
                cap = Convert.ToInt32(capital);
            }
            if (district == "" || district == null)
            {
                dis = 0;
            }
            else
            {
                dis = Convert.ToInt32(district);
            }
            if (hotel == "" || hotel == null)
            {
                hot = 0;
            }
            else
            {
                hot = Convert.ToInt32(hotel);
            }
            return View(dc.SearchGuestsByCapitalDistrictAndHotel(cap,dis,hot, fDate, tDate));
        }
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Capitals()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                ViewBag.regionId = new SelectList(dc.tblRegions.OrderBy(r => r.regionName).ToList(), "regionId", "regionName");
                return View();
            }               
        }
        [HttpPost]
        public ActionResult Capitals(CapitalCity capital)
        {
            if (ModelState.IsValid) 
            {
                using (HotelEntities db = new HotelEntities())
                {
                    db.CapitalCities.Add(capital);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        public JsonResult CheckCapitalName(string capitalName)
        {
            using (HotelEntities db = new HotelEntities())
            {
                System.Threading.Thread.Sleep(100);
                int value = db.CapitalCities.Where(u => u.capitalName == capitalName).Count();
                if (value != 0)
                {
                    return Json(value);
                }
                else
                {
                    return Json(0);
                }
            }
        }
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Districts()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                ViewBag.capitalId = new SelectList(dc.CapitalCities.OrderBy(r => r.capitalName).ToList(), "capitalId", "capitalName");
                return View();
            }
        }
        [HttpPost]
        public ActionResult Districts(District district)
        {
            if (ModelState.IsValid)
            {
                using (HotelEntities db = new HotelEntities())
                {
                    db.Districts.Add(district);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        public JsonResult CheckDistrictName(string districtName)
        {
            using (HotelEntities db = new HotelEntities())
            {
                System.Threading.Thread.Sleep(100);
                int value = db.Districts.Where(u => u.districtName == districtName).Count();
                if (value != 0)
                {
                    return Json(value);
                }
                else
                {
                    return Json(0);
                }
            }
        }
    }
}

Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Immigration.Models;
using Immigration.ViewModel;

namespace Immigration.Controllers
{

    public class GuestsController : Controller
    {
        private HotelEntities db = new HotelEntities();
        [Authorize(Roles = "Hotel Staff")]
        public ActionResult Index()
        {
            Getway dc = new Getway();
            string userName = Convert.ToString(Session["userName"]);
            var guests = dc.GuestsList().Where(g => g.addedBy == userName);
            return View(guests);
        }
        [HttpPost]
        public ActionResult Index(string countryId, string fromDate, string toDate)
        {
            Getway dc = new Getway();
            DateTime date = DateTime.Now;
            int country;
            string fDate = string.Format("{0:MM/dd/yyyy}", date);
            string tDate = string.Format("{0:MM/dd/yyyy}", date);
            if (fromDate != "" || fromDate != null)
            {
                fDate = fromDate;
            }
            if (toDate == "" || toDate == null)
            {
                tDate = toDate;
            }
            if (countryId == "" || countryId == null)
            {
                country = 0;
            }
            else
            {
                country = Convert.ToInt32(countryId);
            }
            return View(dc.SearchGuests(country, fDate, tDate));
        }
        public JsonResult LoadCountry()
        {
            using(HotelEntities db = new HotelEntities())
            {
                return Json(db.Countries.ToList());
            }
        }
        [Authorize(Roles = "Hotel Staff")]
        public ActionResult Create()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                string userName = Convert.ToString(Session["userName"]);
                ViewBag.hotelId = dc.tblUsers.Where(u => u.userName == userName).FirstOrDefault().assignedHotel;
                DateTime date = DateTime.Now;
                ViewBag.ddd = string.Format("{0:MM/dd/yyyy}", date);
                ViewBag.guestNationality = new SelectList(dc.Countries.OrderBy(c => c.CountryName).ToList(), "ID", "CountryName");
                return View();
            }
        }
        public ActionResult Save(tblGuest guest)
        {
            string fileName = Path.GetFileNameWithoutExtension(guest.ImageFile.FileName);
            string extension = Path.GetExtension(guest.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            guest.guestDocuments = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            guest.ImageFile.SaveAs(fileName);
            using (HotelEntities db = new HotelEntities())
            {
                db.tblGuests.Add(guest);
                db.SaveChanges();
            }
            var result = 1;
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Hotel Staff")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGuest guest = db.tblGuests.Find(id);
            ViewBag.ID = new SelectList(db.Countries, "ID", "CountryName");
            if (guest == null)
            {
                return HttpNotFound();
            }
            return View(guest);
        }

        [HttpPost]
        public ActionResult Edit(tblGuest guest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(guest);
        }
        [Authorize(Roles = "Hotel Staff")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            tblGuest guest = db.tblGuests.Find(id);
            db.tblGuests.Remove(guest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Immigration.Models;

namespace Immigration.Controllers
{
    [Authorize(Roles = "Admin,Immigration Staff")]
    public class HotelsController : Controller
    {
        private HotelEntities db = new HotelEntities();
        public ActionResult Index()
        {
            Getway dc = new Getway();            
            return View(dc.HotelList());
        }
        [HttpPost]
        public ActionResult Index(string regionId, string fromDate, string toDate)
        {
            Getway dc = new Getway();
            DateTime date = DateTime.Now;
            int region;
            string fDate = string.Format("{0:MM/dd/yyyy}", date);
            string tDate = string.Format("{0:MM/dd/yyyy}", date);
            if (fromDate !="" || fromDate != null)
            {
                fDate = fromDate;
            }
            if(toDate=="" || toDate == null)
            {
                tDate = toDate;
            }
            if (regionId == "" || regionId == null)
            {
                region = 0;                
            }
            else
            {
                region = Convert.ToInt32(regionId);                
            }
            return View(dc.SearchHotels(region, fDate, tDate));
        }
        public ActionResult Create()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                DateTime date = DateTime.Now;
                ViewBag.ddd = string.Format("{0:MM/dd/yyyy}", date);
                ViewBag.regionId = new SelectList(dc.tblRegions.OrderBy(r => r.regionName).ToList(), "regionId", "regionName");
                ViewBag.capitalId = new SelectList(dc.CapitalCities.OrderBy(c => c.capitalName).ToList(), "capitalId", "capitalName");
                ViewBag.districtId = new SelectList(dc.Districts.OrderBy(r => r.districtName).ToList(), "districtId", "districtName");
                return View();
            }
        }
        [HttpPost]
        public ActionResult Create(tblHotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.tblHotels.Add(hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHotel hotel = db.tblHotels.Find(id);
            ViewBag.regionId = new SelectList(db.tblRegions.ToList(), "regionId", "regionName");
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }
        [HttpPost]
        public ActionResult Edit(tblHotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            tblHotel hotel = db.tblHotels.Find(id);
            db.tblHotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult AllCapital(int id)
        {
            using(HotelEntities db = new HotelEntities())
            {
                return Json(db.CapitalCities.Where(c=> c.regionId ==id).ToList());
            }

        }
        public JsonResult AllDistrict(int id)
        {
            using (HotelEntities db = new HotelEntities())
            {
                var dd = db.Districts.Where(d => d.capitalId == id).ToList();
                return Json(dd);
            }
        }
        public JsonResult AllRegion()
        {
            using(HotelEntities db = new HotelEntities())
            {
                return Json(db.tblRegions.ToList());
            }
        }
    }
}

Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="../../template/assets/images/favicon.png">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="../../template/assets/libs/flot/css/float-chart.css" rel="stylesheet">
    <script src="../../template/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <link href="../../template/dist/css/style.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../template/assets/extra-libs/multicheck/multicheck.css">
    <link href="../../template/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
    @*<link href="~/Content/buttons.dataTables.min.css" rel="stylesheet" />*@
    <link href="../../template/assets/libs/toastr/build/toastr.min.css" rel="stylesheet">
    @*<link href="~/Content/Site.css" rel="stylesheet" />*@
    <style>
        .error {
            color: red
        }
    </style>
</head>

<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md">
                <div class="navbar-header" data-logobg="skin5">
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <a class="navbar-brand" href="@Url.Action("Index","Admin")">
                        <b class="logo-icon p-l-10">
                            <img src="../../template/assets/images/logo-icon.png" alt="homepage" class="light-logo" style="width:32px; height:30px" />
                        </b>
                        <span class="logo-text">
                            <img src="../../template/assets/images/logo-text.png" alt="homepage" class="light-logo" />

                        </span>
                    </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        @if (Session["userName"] != null && Convert.ToString(Session["userName"]) != "")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><img src="../../template/assets/images/users/1.jpg" alt="user" class="rounded-circle" width="31"></a>
                                <div class="dropdown-menu dropdown-menu-right user-dd animated">
                                    <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> Welcome @Session["userName"]</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("PasswordReset", "Accounts")"><i class="ti-lock m-r-5 m-l-5"></i> Change Password</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Logout", "Accounts")"><i class="ti-power-off m-r-5 m-l-5"></i> Logout</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        
                        @if (!User.IsInRole("Hotel Staff"))
                        {
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Admin")" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Accounts")" aria-expanded="false"><i class="fas fa-key"></i><span class="hide-menu">Users</span></a></li>
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Hotels")" aria-expanded="false"><i class="mdi mdi-hospital-building"></i><span class="hide-menu">Hotels</span></a></li>
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Guest", "Admin")" aria-expanded="false"><i class="mdi mdi-account-multiple-plus"></i><span class="hide-menu">Guests</span></a></li>
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Capitals", "Admin")" aria-expanded="false"><i class="fas fa-list-alt"></i><span class="hide-menu">Capitals</span></a></li>
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Districts", "Admin")" aria-expanded="false"><i class="fas fa-map"></i><span class="hide-menu">Districts</span></a></li>
                        }
                        else
                        {
                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index", "Guests")" aria-expanded="false"><i class="mdi mdi-account-multiple-plus"></i><span class="hide-menu">Guests</span></a></li>
                        }
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer class="footer text-center">
                All Rights Reserved by Izone Solution. Designed and Developed by <a href="https://izonesolution.com/">https://izonesolution.com</a>.
            </footer>
        </div>
    </div>
    @*<script src="../../template/assets/libs/jquery/dist/jquery.min.js"></script>*@
    <script src="../../template/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="../../template/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../../template/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="../../template/assets/extra-libs/sparkline/sparkline.js"></script>
    <script src="../../template/dist/js/waves.js"></script>
    <script src="../../template/dist/js/sidebarmenu.js"></script>
    <script src="../../template/dist/js/custom.min.js"></script>
    <script src="../../template/assets/libs/flot/excanvas.js"></script>
    <script src="../../template/assets/libs/flot/jquery.flot.js"></script>
    <script src="../../template/assets/libs/flot/jquery.flot.pie.js"></script>
    <script src="../../template/assets/libs/flot/jquery.flot.time.js"></script>
    <script src="../../template/assets/libs/flot/jquery.flot.stack.js"></script>
    <script src="../../template/assets/libs/flot/jquery.flot.crosshair.js"></script>
    <script src="../../template/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
    <script src="../../template/dist/js/pages/chart/chart-page-init.js"></script>
    @*<script src="../../assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>*@
    <script src="../../template/assets/extra-libs/DataTables/datatables.min.js"></script>
    <script src="~/Scripts/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/buttons.print.min.js"></script>
    <script src="../../template/assets/extra-libs/multicheck/datatable-checkbox-init.js"></script>
    <script src="../../template/assets/extra-libs/multicheck/jquery.multicheck.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="../../template/assets/libs/toastr/build/toastr.min.js"></script>
</body>
</html>