Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Immigration.Models;
using System.Data.Entity;
using System.Web.UI;

namespace Immigration.Controllers
{    
    public class AccountsController : Controller
    {
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Index()
        {
            Getway db = new Getway();
            ViewBag.hotelUser = db.HotelUsers();
            ViewBag.immigrationUser = db.ImmigrationUsers();
            return View();
        }
        [Authorize(Roles = "Admin,Immigration Staff")]
        public ActionResult Register()
        {
            using (HotelEntities dc = new HotelEntities())
            {
                ViewBag.hotelId = new SelectList(dc.tblHotels.ToList(), "hotelId", "hotelName");
                ViewBag.typeId = new SelectList(dc.tblUserTypes.ToList(), "typeId", "typeName");
                DateTime date = DateTime.Now;
                ViewBag.ddd = string.Format("{0:MM/dd/yyyy}", date);
                return View();
            }
        }
        [HttpPost]
        public ActionResult Register(tblUser user)
        {
            using (HotelEntities dc = new HotelEntities())
            {
                if (ModelState.IsValid)
                {
                    if (user.userType != 3)
                    {
                        user.assignedHotel = 0;
                    }
                    string name = FormsAuthentication.HashPasswordForStoringInConfigFile(user.userName, "SHA1");
                    user.userHash = name;
                    string pass = FormsAuthentication.HashPasswordForStoringInConfigFile(user.password, "SHA1");
                    user.passwordHash = pass;
                    dc.tblUsers.Add(user);
                    dc.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(tblUser user, string ReturnUrl = "")
        {
            using (HotelEntities dc = new HotelEntities())
            {
                string name = FormsAuthentication.HashPasswordForStoringInConfigFile(user.userName, "SHA1");
                user.userHash = name;
                string pass = FormsAuthentication.HashPasswordForStoringInConfigFile(user.password, "SHA1");
                user.passwordHash = pass;
                var count = dc.tblUsers.Where(u => u.userHash == user.userHash && u.passwordHash == user.passwordHash && u.activeStatus==1).Count();
                if (count > 0)
                {
                    Session["userName"] = user.userName;
                    FormsAuthentication.SetAuthCookie(user.userName, false);
                    if (ReturnUrl == null || ReturnUrl == "")
                    {
                        var uType = dc.tblUsers.Where(a => a.userName == user.userName).FirstOrDefault().userType;
                        if (uType != 3)
                        {
                            return RedirectToAction("Index", "Admin");
                        }
                        else
                        {
                            return RedirectToAction("Index", "Guests");
                        }
                    }
                    else
                    {
                        return Redirect(ReturnUrl);
                    }
                }
                ViewBag.error = "user name or password not match.";
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session["userName"] = "";
            return RedirectToAction("Login");
        }
        public ActionResult ChangeStatus(int id)
        {
            using (HotelEntities dc = new HotelEntities())
            {
                var user = dc.tblUsers.Find(id);
                int status = Convert.ToInt32(user.activeStatus);
                if (status == 1)
                {
                    user.activeStatus = 2;
                }
                else
                {
                    user.activeStatus = 1;
                }
                if (user != null)
                {
                    dc.Entry(user).State = EntityState.Modified;
                    dc.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        public JsonResult CheckUserName(string userName)
        {
            using (HotelEntities db = new HotelEntities())
            {
                System.Threading.Thread.Sleep(100);
                int value = db.tblUsers.Where(u => u.userName == userName).Count();
                if (value != 0)
                {
                    return Json(value);
                }
                else
                {
                    return Json(0);
                }
            }
        }
        [Authorize]
        public ActionResult PasswordReset()
        {
            return View();
        }        
        public JsonResult ResetPassword(string userName, string oldPass, string newPass)
        {
            var dd = 0;
            using (HotelEntities db = new HotelEntities())
            {
                var user = db.tblUsers.Where(u => u.userName == userName && u.password == oldPass).FirstOrDefault();
                if (user != null)
                {
                    user.password = newPass;
                    string pass = FormsAuthentication.HashPasswordForStoringInConfigFile(newPass, "SHA1");
                    user.passwordHash = pass;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    dd = 1;
                    return Json(dd);
                }
                else
                {
                    return Json(dd);
                }
            }
        }
        public JsonResult CheckUserType(string userName)
        {
            using (HotelEntities db = new HotelEntities())
            {
                var uType = db.tblUsers.Where(a => a.userName == userName).FirstOrDefault().userType;
                return Json(uType);
            }
        }
    }
}

Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
@*<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="@Url.Action("Register","Accounts")" class="btn btn-success">Create New</a>
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>*@
<div class="card">
    <div class="card-body">
        <div style="width:90%; float:left;"><h4 class="card-title pull-left">Hotel User</h4></div>
        <div style="width:10%; float:right;"><a href="@Url.Action("Register","Accounts")" class="btn btn-success pull-right">Create New</a></div>

        <div class="table-responsive">
            <table id="tbl_config" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            Person Name
                        </th>
                        <th>
                            User Name
                        </th>
                        <th>
                            User Type
                        </th>
                        <th>
                            Assigned Hotel
                        </th>
                        <th>
                            Status
                        </th>
                        <th>Added by</th>
                        <th>Added Date</th>

                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.hotelUser)
                    {
                        <tr>
                            <td>
                                @item.personName
                            </td>
                            <td>
                                @item.userName
                            </td>
                            <td>
                                @item.typeName
                            </td>
                            <td>
                                @item.hotelName
                            </td>
                            <td>
                                @item.statusName
                            </td>
                            <td>
                                @item.addedBy
                            </td>
                            <td>
                                @item.addedDate
                            </td>
                            <td>
                                @if (item.statusName == "Enabled")
                                {
                                    <input type="button" id="btnStatus1" onclick="StatusChange(@item.userId,1)" value="Disable" class="btn-sm stat btn-warning" />
                                }
                                else
                                {
                                    <input type="button" id="btnStatus1" onclick="StatusChange(@item.userId,2)" value="Enable" class="btn-sm stat btn-success" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Immigration Staff / Admin Users</h5>
        <div class="table-responsive">
            <table id="tbl2_config" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            Person Name
                        </th>
                        <th>
                            User Name
                        </th>
                        <th>
                            User Type
                        </th>
                        <th>
                            Status
                        </th>
                        <th>Added by</th>
                        <th>Added Date</th>

                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.immigrationUser)
                    {
                        <tr>
                            <td>
                                @item.personName
                            </td>
                            <td>
                                @item.userName
                            </td>
                            <td>
                                @item.typeName
                            </td>
                            <td>
                                @item.statusName
                            </td>
                            <td>
                                @item.addedBy
                            </td>
                            <td>
                                @item.addedDate
                            </td>
                            <td>
                                @if (item.statusName == "Enabled")
                                {
                                    @*<a href="javascript:void(0)" id="btnStatus" onclick="StatusChange(@item.userId)" class="btn-sm btn-warning" >Disable</a>*@
                                    <input type="button" id="btnStatus" onclick="StatusChange(@item.userId,1)" value="Disable" class="btn-sm stat btn-warning" />
                                }
                                else
                                {
                                    <input type="button" id="btnStatus" onclick="StatusChange(@item.userId,2)" value="Enable" class="btn-sm stat btn-success" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#tbl_config').DataTable({
            "bFilter": false,
            "lengthChange": false,
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'print',
                    text: '<span class="fas fa-print"> Print</span>',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5]
                    },
                    className: 'btn btn-success'
                }
            ]
        });
        $('#tbl2_config').DataTable({
            "bFilter": false,
            "lengthChange": false
        });
    });
    function StatusChange(id,stat) {
        swal({
            title: "Are you sure to change?",
            text: "User info will be changed..!!!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                var Id = id;
                var val = stat;
                $.ajax({
                    type: "POST",
                    url: "/Accounts/ChangeStatus?id=" + Id,
                    success: function () {
                        if (val == 1) {
                            swal({
                                icon: "success",
                                title: "successfully disabled"
                            })
                            .then((confirm) => {
                                if (confirm == true) {
                                    location.reload();
                                }
                            });
                        } else {
                            swal({
                                icon: "success",
                                title: "successfully enabled"

                            })
                            .then((confirm) => {
                                if (confirm == true) {
                                    location.reload();
                                }
                            });
                        }
                    }
                });
            } else {
                swal("Your data is safe!");
            }
        });
    };
</script>

Views/Accounts/Login.cshtml
@model Immigration.Models.tblUser
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <style>
        body {
            background: #222D32;
            font-family: 'Roboto', sans-serif;
        }

        .login-box {
            margin-top: 75px;
            height: auto;
            background: #1A2226;
            text-align: center;
            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
        }

        .login-key {
            margin-top: 26px;
            height: 88px;
            font-size: 80px;
            line-height: 100px;
            background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .login-title {
            text-align: center;
            font-size: 30px;
            letter-spacing: 2px;
            margin-top: -5px;
            font-weight: bold;
            color: #ECF0F5;
        }

        .login-form {
            margin-top: 25px;
            text-align: left;
        }

        input[type=text] {
            background-color: #e8f0fe;
            border: none;
            border-bottom: 2px solid #0DB8DE;
            border-top: 0px;
            border-radius: 0px;
            font-weight: bold;
            outline: 0;
            margin-bottom: 20px;
            padding-left: 10px;
            color: #ECF0F5;
        }
        input[type=password] {
            background-color: #e8f0fe;
            border: none;
            border-bottom: 2px solid #0DB8DE;
            border-top: 0px;
            border-radius: 0px;
            font-weight: bold;
            outline: 0;
            margin-bottom: 20px;
            padding-left: 10px;
            color: #000;
        }

        /*input[type=password] {
            background-color: #1A2226;
            border: none;
            border-bottom: 2px solid #0DB8DE;
            border-top: 0px;
            border-radius: 0px;
            font-weight: bold;
            outline: 0;
            padding-left: 0px;
            margin-bottom: 20px;
            color: #ECF0F5;
        }
*/
        .form-group {
            margin-bottom: 40px;
            outline: 0px;
        }

        .form-control:focus {
            border-color: inherit;
            -webkit-box-shadow: none;
            box-shadow: none;
            border-bottom: 2px solid #0DB8DE;
            outline: 0;
            background-color: #1A2226;
            color: #ECF0F5;
        }

        input:focus {
            outline: none;
            box-shadow: 0 0 0;
        }

        label {
            margin-bottom: 0px;
        }

        .form-control-label {
            font-size: 10px;
            color: #6C6C6C;
            font-weight: bold;
            letter-spacing: 1px;
        }

        .btn-outline-primary {
            border-color: #0DB8DE;
            color: #0DB8DE;
            border-radius: 0px;
            font-weight: bold;
            letter-spacing: 1px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

        .login-btm {
            float: left;
        }

        .login-button {
            padding-right: 0px;
            text-align: right;
            margin-bottom: 25px;
        }

        .login-text {
            text-align: left;
            padding-left: 0px;
            color: #A2A4A4;
        }

        .loginbttm {
            padding: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"> </div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-user" aria-hidden="true"> </i>
                </div>
                <div class="col-lg-12 login-title">
                    User Login
                </div>
                <h4 class="text-danger">
                    @ViewBag.error
                </h4>
                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        @using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="form-control-label"> USERNAME</label>
                                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                            </div>
                            <div class="form-group">
                                <label class="form-control-label"> PASSWORD</label>
                                <input type="password" id="password" name="password" class="form-control" required />
                            </div>
                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <input type="submit" value="Login" class="btn btn-outline-primary" />
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"> </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Accounts/PasswordReset.cshtml
@{
    Layout = "~/Views/Shared/_Admin.cshtml";
    ViewBag.Title = "Password Reset";
}
<div class="card" style="border-radius:10px">
    <div class="card-body wizard-content">
        <h4 class="card-title" style="padding-left:30px;">Reset Password</h4>
        <div style="background:#eeeeee;padding:30px;border-radius:10px;">
            <form id="uForm" method="post" novalidate="novalidate">
                <input type="hidden" id="userName" name="userName" value="@Session["userName"]" />
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-md-2">Old Password</label>
                        <div class="col-md-10">
                            <input type="password" class="form-control col-md-10" id="oldPass" name="oldPass"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">New Password</label>
                        <div class="col-md-10">
                            <input type="password" class="form-control col-md-10" id="newPass" name="newPass"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Re-write Password</label>
                        <div class="col-md-10">
                            <input type="password" class="form-control col-md-10" id="rePass" name="rePass"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Reset Password" id="btnSave" class="btn btn-warning" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#uForm").validate({
            rules: {
                oldPass: {
                    required: true
                },
                newPass: {
                    required: true,
                    minlength: 6
                },
                rePass: {
                    required: true,
                    equalTo: "#newPass"
                }
            },
            messages: {
                oldPass: "old password is required.",
                newPass: {
                    required: "new password is required.",
                    minlength: "password must be at least 6 characters long"
                },
                rePass: {
                    required: "re-write password is required.",
                    equalTo: "please enter the same password as above."
                }
            },
            submitHandler: function () {
                var uname = $('#userName').val();
                var opass = $('#oldPass').val();
                var npass = $('#newPass').val();
                var data = {
                    userName: uname,
                    oldPass: opass,
                    newPass: npass
                };
                $.ajax({
                    type: "POST",
                    url: "/Accounts/ResetPassword",
                    data: data,
                    success: function (dd) {
                        if (dd == 1) {
                            swal({
                                icon: "success",
                                title: "successfully done!!"
                            }).then((confirm) => {
                                if (confirm == true) {
                                    $.post("@Url.Action("CheckUserType", "Accounts")", { userName: uname }
                                        , function (data) {
                                            if (data != 3) {
                                                window.location.href = "/Admin/Index";
                                            } else {
                                                window.location.href = "/Guests/Index";
                                            }
                                        });
                                }
                            });
                        }
                        else {
                            swal({
                                icon: "error",
                                title: "sorry..!!",
                                text: "old password not match."
                            })
                        }
                    }
                });
            }
        });
    });
</script>